apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-checker-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helm-checker-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-checker-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: helm-checker-sa
  namespace: default
roleRef:
  kind: Role
  name: helm-checker-role
  apiGroup: rbac.authorization.k8s.io
